name: bijen
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - nltk
  - requests
  - beautifulsoup4
  - opencv
  - jupyter
  - nbclassic
  - sqlite
  - pyreadstat
  - spacy
  - ipywidgets
  - pip
  - pip:
      - transformers
